window.WhacConfig = {
  currencies: [
    { code:'USD', symbol:'$',  flag:'🇺🇸', name:'US Dollar'      },
    { code:'EUR', symbol:'€',  flag:'🇪🇺', name:'Euro'            },
    { code:'CHF', symbol:'Fr', flag:'🇨🇭', name:'Franc suisse'    },
    { code:'NGN', symbol:'₦',  flag:'🇳🇬', name:'Naira nigérian'  },
    { code:'AOA', symbol:'Kz', flag:'🇦🇴', name:'Kwanza angolais' },
    { code:'MZN', symbol:'MT', flag:'🇲🇿', name:'Metical mozamb.' },
  ],
  languages: [
    { code:'fr', label:'Français',  flag:'🇫🇷' },
    { code:'en', label:'English',   flag:'🇬🇧' },
    { code:'pt', label:'Português', flag:'🇵🇹' },
    { code:'es', label:'Español',   flag:'🇪🇸' },
    { code:'sw', label:'Kiswahili', flag:'🇰🇪' },
  ],
  i18n: {
    fr: {
      balance:'Solde', sound:'Son', language:'Langue', currency:'Devise', menu:'Menu',
      soundOn:'Activé', soundOff:'Désactivé',
      hits:'Frappes', wagered:'Misé', session:'Session RTP',
      insufficient:'Solde insuffisant',
      chooseBet:'Choisissez une mise et tapez !',
      frenzyTitle:'🌟 MODE FRENZY !',
      frenzyMsg:'Pas de pièges — multiplicateurs boostés !',
      trap:'💣 Piège !', legend:'💰 LÉGENDAIRE !', epic:'🤑 ÉPIQUE !',
      rules:'Règles du jeu',
    },
    en: {
      balance:'Balance', sound:'Sound', language:'Language', currency:'Currency', menu:'Menu',
      soundOn:'On', soundOff:'Off',
      hits:'Hits', wagered:'Wagered', session:'Session RTP',
      insufficient:'Insufficient balance',
      chooseBet:'Choose a bet and whack!',
      frenzyTitle:'🌟 FRENZY MODE!',
      frenzyMsg:'No traps — boosted multipliers!',
      trap:'💣 Trap!', legend:'💰 LEGENDARY!', epic:'🤑 EPIC!',
      rules:'Game Rules',
    },
    pt: {
      balance:'Saldo', sound:'Som', language:'Idioma', currency:'Moeda', menu:'Menu',
      soundOn:'Ativado', soundOff:'Desativado',
      hits:'Golpes', wagered:'Apostado', session:'RTP Sessão',
      insufficient:'Saldo insuficiente',
      chooseBet:'Escolha uma aposta e bata!',
      frenzyTitle:'🌟 MODO FRENZY!',
      frenzyMsg:'Sem armadilhas — multiplicadores turbinados!',
      trap:'💣 Armadilha!', legend:'💰 LENDÁRIO!', epic:'🤑 ÉPICO!',
      rules:'Regras do jogo',
    },
    es: {
      balance:'Saldo', sound:'Sonido', language:'Idioma', currency:'Divisa', menu:'Menú',
      soundOn:'Activado', soundOff:'Desactivado',
      hits:'Golpes', wagered:'Apostado', session:'RTP Sesión',
      insufficient:'Saldo insuficiente',
      chooseBet:'¡Elige una apuesta y golpea!',
      frenzyTitle:'🌟 ¡MODO FRENZY!',
      frenzyMsg:'¡Sin trampas — multiplicadores potenciados!',
      trap:'💣 ¡Trampa!', legend:'💰 ¡LEGENDARIO!', epic:'🤑 ¡ÉPICO!',
      rules:'Reglas del juego',
    },
    sw: {
      balance:'Salio', sound:'Sauti', language:'Lugha', currency:'Sarafu', menu:'Menyu',
      soundOn:'Imewashwa', soundOff:'Imezimwa',
      hits:'Mapigo', wagered:'Kilichowekwa', session:'RTP ya Kikao',
      insufficient:'Salio haitoshi',
      chooseBet:'Chagua dau na piga!',
      frenzyTitle:'🌟 HALI YA FRENZY!',
      frenzyMsg:'Hakuna mitego — vizidishi vilivyoimarishwa!',
      trap:'💣 Mtego!', legend:'💰 YA HADITHI!', epic:'🤑 YA AJABU!',
      rules:'Sheria za Mchezo',
    },
  },
};
